
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

// Using gemini-3-pro for complex coding tasks.
const GEMINI_MODEL = 'gemini-3-pro-preview';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export class GeminiError extends Error {
  constructor(public message: string, public type: 'safety' | 'rate-limit' | 'network' | 'unknown' = 'unknown') {
    super(message);
    this.name = 'GeminiError';
  }
}

const SYSTEM_INSTRUCTION = `You are a world-class Full-Stack Product Engineer and Creative Technologist. Your specialty is "Artifact Animation": transforming static inputs (sketches, photos, notes) into high-fidelity, interactive, and visually breathtaking single-page web applications.

CORE MISSION:
Take any user input—be it a napkin sketch, a whiteboard diagram, a photo of a real-world object, or a structured design—and output a "Production-Ready" interactive experience that feels like a premium digital product.

VISUAL & DESIGN DIRECTIVES:
1. **Aesthetic Excellence**: Aim for a modern "Software-as-a-Service" (SaaS) or high-end consumer tech look. Use deep shadows, subtle gradients, and plenty of white space.
2. **Color Palette**: Use a sophisticated color palette (e.g., Zinc/Slate for dark mode, subtle accents like Indigo, Emerald, or Rose).
3. **Typography**: Use clean, modern sans-serif fonts (Inter, Geist, or system-ui). Use varying font weights to create a clear hierarchy.
4. **Glassmorphism & Depth**: Use backdrop-blur, subtle borders (1px with low opacity), and layering to create depth.
5. **Iconography**: Use Lucide Icons (load via <script src="https://unpkg.com/lucide@latest"></script>) for a professional look. Fall back to Emojis or Inline SVGs only if necessary.
6. **Animations**: Every interaction should feel fluid. Use CSS transitions for hovers and state changes. Use @keyframes for entrance animations (fade-in, slide-up).

FUNCTIONAL DIRECTIVES:
1. **Analyze & Gamify**: 
    - **Sketches**: Faithfully reproduce the layout but "upgrade" the components to professional UI.
    - **Objects (e.g., a Desk)**: Create a "Zen Mode" organizer or an interactive inventory tracker.
    - **Documents**: Turn them into interactive dashboards with charts (use simple CSS/SVG bars) and filters.
2. **NO EXTERNAL ASSETS**: 
    - **STRICT RULE**: Do NOT use external <img src="..."> tags. 
    - **RECREATION**: Use CSS, SVGs, or Emojis to build visuals. If the user uploaded a picture of a cat, draw a stylized cat using CSS or use a 🐈 emoji.
3. **Self-Contained Power**: Output a SINGLE HTML file. Use Tailwind CSS (via CDN) for styling. All JS logic must be embedded in <script> tags.

RESPONSE FORMAT:
Return ONLY the raw HTML code. Do not include markdown fences (like \`\`\`html). Start with <!DOCTYPE html> immediately.`;

export async function bringToLife(prompt: string, fileBase64?: string, mimeType?: string): Promise<string> {
  const parts: any[] = [];
  
  const finalPrompt = fileBase64 
    ? "Analyze this input carefully. Detect every functional element. Re-imagine this as a stunning, premium interactive web application with a modern UI, smooth animations, and sophisticated styling. Use Tailwind CSS and Lucide icons. DO NOT use external image URLs." 
    : prompt || "Create a groundbreaking, highly interactive demo app that showcases peak UI/UX design and complex functionality.";

  parts.push({ text: finalPrompt });

  if (fileBase64 && mimeType) {
    parts.push({
      inlineData: {
        data: fileBase64,
        mimeType: mimeType,
      },
    });
  }

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: {
        parts: parts
      },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0.7,
      },
    });

    // Handle empty or missing candidate responses
    if (!response.candidates || response.candidates.length === 0) {
      throw new GeminiError("No response generated by the model.", "unknown");
    }

    const candidate = response.candidates[0];

    // Handle safety filtering
    if (candidate.finishReason === 'SAFETY') {
      throw new GeminiError("The request was blocked by safety filters. Please try another input.", "safety");
    }

    let text = response.text || "";

    if (!text || text.trim().length === 0) {
      throw new GeminiError("The model returned an empty response.", "unknown");
    }

    // Cleanup markdown fences if present
    text = text.replace(/^```html\s*/i, '').replace(/^```\s*/, '').replace(/```$/, '');

    return text;
  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    
    if (error instanceof GeminiError) {
      throw error;
    }

    // Handle common HTTP error codes
    const status = error.status || (error.response && error.response.status);
    if (status === 429) {
      throw new GeminiError("Too many requests. Please wait a moment before trying again.", "rate-limit");
    } else if (status === 500 || status === 503) {
      throw new GeminiError("The AI service is temporarily unavailable. Please try again later.", "network");
    } else if (error.message?.includes("fetch")) {
      throw new GeminiError("Connection error. Please check your internet and try again.", "network");
    }

    throw new GeminiError(error.message || "An unexpected error occurred while bringing the artifact to life.", "unknown");
  }
}
